--------------------------------------------------------
--  File created - Friday-June-28-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table JL_MEDIAINFO
--------------------------------------------------------

  CREATE TABLE "PRACTICE"."JL_MEDIAINFO" 
   (	"MEDIA_NAME" VARCHAR2(100 BYTE), 
	"MEDIA" BLOB, 
	"MEDIA_TYPE" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("MEDIA") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into PRACTICE.JL_MEDIAINFO
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_JL_MDIA_INFO_MDIA_NM
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRACTICE"."PK_JL_MDIA_INFO_MDIA_NM" ON "PRACTICE"."JL_MEDIAINFO" ("MEDIA_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table JL_MEDIAINFO
--------------------------------------------------------

  ALTER TABLE "PRACTICE"."JL_MEDIAINFO" MODIFY ("MEDIA_NAME" NOT NULL ENABLE);
  ALTER TABLE "PRACTICE"."JL_MEDIAINFO" MODIFY ("MEDIA" NOT NULL ENABLE);
  ALTER TABLE "PRACTICE"."JL_MEDIAINFO" ADD CONSTRAINT "PK_JL_MDIA_INFO_MDIA_NM" PRIMARY KEY ("MEDIA_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRACTICE"."JL_MEDIAINFO" MODIFY ("MEDIA_TYPE" NOT NULL ENABLE);
  ALTER TABLE "PRACTICE"."JL_MEDIAINFO" ADD CONSTRAINT "CK_JL_MDA_INFO_TYPE" CHECK (media_type in ('V','B')) ENABLE;
